let caves = [
    "Bleakcoast Cave",
    "Blind Cliff Cave",
    "Bloated Man's Grotto",
    "Bonechill Passage",
    "Boulderfall Cave",
    "Brinewater Grotto",
    "Brittleshin Pass",
    "Broken Fang Cave",
    "Broken Helm Hollow",
    "Broken Oar Grotto",
    "Brood Cavern",
    "Chillwind Depths",
    "Clearspring Cave",
    "Cold Rock Pass",
    "Cragslane Cavern",
    "Cragwallow Slope",
    "Cronvangr Cave",
    "Crystaldrift Cave",
    "Darkshade",
    "Darkwater Pass",
    "Duskglow Crevice",
    "Fallowstone Cave",
    "Forsaken Cave",
    "Glenmoril Coven",
    "Gloomreach",
    "Graywinter Watch",
    "Greywater Grotto",
    "Haemar's Shame",
    "Halldir's Cairn",
    "Hob's Fall Cave",
    "Liar's Retreat",
    "Lost Echo Cave",
    "Lost Knife Hideout",
    "Mara's Eye Den",
    "Moss Mother Cavern",
    "Movarth's Lair",
    "Orotheim",
    "Pinemoon Cave",
    "Pinepeak Cavern",
    "Purewater Run",
    "Ravenscar Hollow",
    "Reachcliff Cave",
    "Redoran's Retreat",
    "Rimerock Burrow",
    "Shadowgreen Cavern",
    "Shimmermist Cave",
    "Sightless Pit",
    "Snapleg Cave",
    "Soljund's Sinkhole",
    "Southfringe Sanctum",
    "Steepfall Burrow",
    "Stillborn Cave",
    "Sunderstone Gorge",
    "Swindler's Den",
    "Tolvald's Cave",
    "Uttering Hills Cave",
    "White River Watch",
    "Yngvild"
]

let dwarvenRuins = [
    "Kagrenzel",
    "Mzinchaleft",
    "Nchuand-Zel",
    "Raldbthar"
]

let militaryForts = [
    "Bloodlet Throne",
    "Broken Tower Redoubt",
    "Cracked Tusk Keep",
    "Darklight Tower",
    "Driftshade Refuge",
    "Faldar's Tooth",
    "Fellglow Keep",
    "Fort Amol",
    "Fort Dunstad",
    "Fort Fellhammer",
    "Fort Greenwall",
    "Fort Greymoor",
    "Fort Hraggstad",
    "Fort Kastav",
    "Fort Neugrad",
    "Fort Snowhawk",
    "Fort Sungard",
    "Gallows Rock",
    "Harmugstahl",
    "High Hrothgar",
    "Ilinalta's Deep",
    "Mistwatch",
    "Morvunskar",
    "Nightcaller Temple",
    "Northwatch Keep",
    "Treva's Watch"
]

let mines = [
    "Bilegulch Mine",
    "Embershard Mine",
    "Fenn's Gulch Mine",
    "Halted Stream Mine",
    "Kolskeggr Mine"
]

let nordicRuins = [
    "Angarvunde",
    "Ansilvund",
    "Arcwind Point",
    "Bleak Falls Barrow",
    "Dead Men's Respite",
    "Deepwood Redoubt",
    "Folgunthur",
    "Forelhost",
    "Frostmere Crypt",
    "Geirmund's Hall",
    "Hag Rock Redoubt",
    "Hag's End",
    "High Gate Ruins",
    "Hillgrund's Tomb",
    "Ironbind Barrow",
    "Lost Valley Redoubt",
    "Ragnvald",
    "Rannveig's Fast",
    "Shalidor's Maze",
    "Shriekwind Bastion",
    "Shroud Hearth Barrow",
    "Silent Moons Camp",
    "Silverdrift Lair",
    "Valthume",
    "Volskygge",
    "Volunruud",
    "Yngol Barrow"
]
