let caves = [
    "Bleakcoast Cave",
    "Blind Cliff Cave",
    "Bloated Man's Grotto",
    "Alftand",
    "Bonechill Passage",
    "Boulderfall Cave",
    "Brinewater Grotto",
    "Brittleshin Pass",
    "Broken Fang Cave",
    "Broken Helm Hollow",
    "Broken Oar Grotto",
    "Bronze Water Cave",
    "Brood Cavern",
    "Bruca's Leap Redoubt",
    "Chillwind Depths",
    "Clearspring Cave",
    "Cold Rock Pass",
    "Cragslane Cavern",
    "Cragwallow Slope",
    "Cronvangr Cave",
    "Crystaldrift Cave",
    "Darkshade",
    "Darkwater Pass",
    "Duskglow Crevice",
    "Eldergleam Sanctuary",
    "Fallowstone Cave",
    "Forsaken Caved",
    "Glenmoril Coven",
    "Gloomreach",
    "Graywinter Watch",
    "Greywater Grotto",
    "Haemar's Shame",
    "Halldir's Cairn",
    "Hob's Fall Cave",
    "Honeystrand Cave",
    "Liar's Retreat",
    "Lost Echo Cave",
    "Lost Knife Hideout",
    "Mara's Eye Den",
    "Moss Mother Cavern",
    "Movarth's Lair",
    "Nightingale Hall",
    "Orotheim",
    "Pinemoon Cave",
    "Pinepeak Cavern",
    "Purewater Run",
    "Ravenscar Hollow",
    "Reachcliff Cave",
    "Reachwater Rock",
    "Rebel's Cairn",
    "Red Eagle Redoubt",
    "Redoran's Retreat",
    "Rimerock Burrow",
    "Septimus Signus's Outpost",
    "Shadowgreen Cavern",
    "Shimmermist Cave",
    "Sightless Pit",
    "Snapleg Cave",
    "Soljund's Sinkhole",
    "Southfringe Sanctum",
    "Steepfall Burrow",
    "Stillborn Cave",
    "Stony Creek Cave",
    "Sunderstone Gorge",
    "Swindler's Den",
    "Tolvald's Cave",
    "Uttering Hills Cave",
    "White River Watch",
    "Wolfskull Cave",
    "Yngvild"
]

let dwarvenRuins = [
    "Alftand",
    "Avanchnzel",
    "Blackreach",
    "Debate Hall",
    "Derelict Pumphouse",
    "Farm Overseer's House",
    "Hall of Rumination",
    "Pumping Station",
    "Reeking Tower",
    "Silent City Catacombs",
    "Silent Ruin",
    "Sinderion's Field Laboratory",
    "War Quarters",
    "Bronze Water Cave",
    "Bthardamz",
    "Deep Folk Crossing",
    "Great Lift at Alftand",
    "Great Lift at Mzinchaleft",
    "Great Lift at Raldbthar",
    "Irkngthand",
    "Kagrenzel",
    "Liar's Retreat",
    "Mzinchaleft",
    "Mzulft",
    "Nchuand-Zel",
    "Purewater Run",
    "Raldbthar",
    "Reachwind Eyrie",
    "Ruins of Bthalft",
    "Ruins of Rkund",
    "Shimmermist Cave",
    "Sightless Pit",
    "Tolvald's Cave",
    "Tower of Mzark"
]

let militaryForts = [
    "Bloodlet Throne",
    "Broken Tower Redoubt",
    "Cracked Tusk Keep",
    "Darklight Tower",
    "Driftshade Refuge",
    "Faldar's Tooth",
    "Fellglow Keep",
    "Fort Amol",
    "Fort Dunstad",
    "Fort Fellhammer",
    "Fort Greenwall",
    "Fort Greymoor",
    "Fort Hraggstad",
    "Fort Kastavb",
    "Fort Neugrad",
    "Fort Snowhawk",
    "Fort Sungard",
    "Gallows Rock",
    "Harmugstahl",
    "High Hrothgar",
    "Ilinalta's Deep",
    "Mistwatch",
    "Morvunskar",
    "Nightcaller Temple",
    "Northwatch Keep",
    "Treva's Watch",
    "Western Watchtower"
]

let mines = [
    "Bilegulch Mine",
    "Cidhna Mine",
    "Dushnikh Mine",
    "Embershard Mine",
    "Fenn's Gulch Mine",
    "Gloombound Mine",
    "Goldenrock Mine",
    "Halted Stream Mine",
    "Iron-Breaker Mine",
    "Kolskeggr Mine",
    "Left Hand Mine",
    "Lost Prospect Mine",
    "Mor Khazgur Mine",
    "Northwind Mine",
    "Quicksilver Mine",
    "Redbelly Mine",
    "Rockwallow Mine",
    "Sanuarach Mine",
    "Steamscorch Mine",
    "Soljund's Sinkhole",
    "Whistling Mine"
]

let nordicRuins = [
    "Angarvunde",
    "Ansilvund",
    "Arcwind Point",
    "Bleak Falls Barrow",
    "Blind Cliff Bastion",
    "Bromjunaar Sanctuary building in Labyrinthian",
    "Dead Men's Respite",
    "Deepwood Redoubt",
    "Dustman's Cairn",
    "Folgunthur",
    "Forelhost",
    "Frostmere Crypt",
    "Geirmund's Hall",
    "Hag Rock Redoubt",
    "Hag's End",
    "High Gate Ruins",
    "Hillgrund's Tomb",
    "Ironbind Barrow",
    "Kilkreath Ruins",
    "Korvanjund",
    "Labyrinthian",
    "Lost Valley Redoubt",
    "Ragnvald",
    "Rannveig's Fast",
    "Saarthal",
    "Shalidor's Maze",
    "Shriekwind Bastion",
    "Shroud Hearth Barrow",
    "Silent Moons Camp",
    "Silverdrift Lair",
    "Skuldafn",
    "Snow Veil Sanctum",
    "Twilight Sepulcher",
    "Ustengrav",
    "Valthume",
    "Volskygge",
    "Volunruud",
    "Yngol Barrow",
    "Ysgramor's Tomb",
    "Four Skull Lookout",
    "Hamvir's Rest",
    "Journeyman's Nook",
    "Kjenstag Ruins",
    "Lost Valkygg",
    "North Skybound Watch",
    "Roadside Ruins",
    "Skytemple Ruins",
    "Hrothmund's Barrow",
    "Windward Ruins",
    "Yorgrim Overlook"
]

let imperialTowers = [
    "Abandoned Prison",
    "Falkreath Watchtower",
    "Pinefrost Tower",
    "Refugees' Rest",
    "Rift Watchtower",
    "Shor's Watchtower",
    "Snowpoint Beacon",
    "Stendarr's Beacon",
    "Whitewatch Tower",
    "Widow's Watch Ruins",
    "Nordic Towers",
    "Bannermist Tower",
    "Bleakwind Bluff",
    "Cradle Stone Tower",
    "Dead Crone Rock",
    "Nilheim",
    "Peak's Shade Tower",
    "South Skybound Watch",
    "Sundered Towers",
    "Valtheim Towers"
]
