let caves = [
    "Bleakcoast Cavetrolls.",
    "Blind Cliff CaveForsworn.",
    "Bloated Man's Grotto",
    "Alftand.",
    "Bonechill Passagemap)",
    "Boulderfall Cave",
    "Brinewater Grotto",
    "Brittleshin Passoccupied by necromancers and skeletons.",
    "Broken Fang Caveleveled vampires.",
    "Broken Helm Hollow",
    "Broken Oar GrottoGrotto.",
    "Bronze Water Caveleveled animals.",
    "Brood Cavernmap)",
    "Bruca's Leap Redoubtrieklings.",
    "Chillwind Depthsinhabited by Falmer, Frostbite Spider, Chaurus.",
    "Clearspring Cave",
    "Cold Rock Passtrap door atop the cliff just southeast of Raven Rock, near the top of the Bulwark.",
    "Cragslane Cavern",
    "Cragwallow Slope",
    "Cronvangr Cave",
    "Crystaldrift Cavebuilt to watch over him and to bring peace to weary travelers.",
    "Darkshadeis inhabited by trolls and is littered with human remains.",
    "Darkwater Pass",
    "Duskglow Crevice",
    "Eldergleam Sanctuary",
    "Fallowstone CaveRiften and a short distance north of Lost Prospect Mine which is inhabited by leveled animals.",
    "Forsaken Cavedraugrs. rieklings. Lodge inhabited by werewolves. coast, containing rieklings and horkers.",
    "Glenmoril CovenGlenmoril Witches.",
    "Gloomreach",
    "Graywinter Watch",
    "Greywater Grottopredatory animals.",
    "Haemar's Shame",
    "Halldir's Cairnthe fierce Halldir.",
    "Hob's Fall Caveskeletons.",
    "Honeystrand Cave",
    "Liar's RetreatKarthwasten which is overtaken by Falmers.",
    "Lost Echo Cave",
    "Lost Knife Hideout",
    "Mara's Eye Den",
    "Moss Mother Cavernnorth of Hunter's Rest and northwest of Half-Moon Mill which is inhabited by bears and spriggans.",
    "Movarth's Lair",
    "Nightingale Hall",
    "Orotheim",
    "Pinemoon Caveby vampires and wolves.",
    "Pinepeak Cavern",
    "Purewater Run",
    "Ravenscar HollowStone.",
    "Reachcliff Cavemap)",
    "Reachwater Rock",
    "Rebel's Cairn",
    "Red Eagle Redoubtlocated east of Markarth.",
    "Redoran's Retreat",
    "Rimerock Burrowoccupied by Vigilants encharmed by conjurer Minorne.",
    "Septimus Signus's OutpostSeptimus Signus has made his home.",
    "Shadowgreen Cavern",
    "Shimmermist Cave",
    "Sightless Pit",
    "Snapleg Caveleveled animals.",
    "Soljund's Sinkholemap)",
    "Southfringe Sanctum",
    "Steepfall Burrow",
    "Stillborn Caveis occupied by falmer, chaurus, and chaurus hunters.",
    "Stony Creek Cave",
    "Sunderstone Gorge",
    "Swindler's Den",
    "Tolvald's Cavesouth-southeast of Ansilvund.",
    "Uttering Hills Cave",
    "White River Watchby the White River bandits.",
    "Wolfskull Cave",
    "Yngvildis occupied by necromancer Arondil, draugr, and ghosts ."
]

let dwarvenRuins = [
    "Alftand",
    "Avanchnzel",
    "Blackreach",
    "Debate Hall",
    "Derelict Pumphouse",
    "Farm Overseer's House",
    "Hall of Rumination",
    "Pumping Station",
    "Reeking Tower",
    "Silent City Catacombs",
    "Silent Ruin",
    "Sinderion's Field Laboratory",
    "War Quarters",
    "Bronze Water Caveleveled animals.",
    "Bthardamz",
    "Deep Folk Crossingof the Reach.",
    "Great Lift at AlftandWayward Pass.",
    "Great Lift at Mzinchaleft",
    "Great Lift at RaldbtharIrkngthand.",
    "Irkngthand",
    "KagrenzelWatchtower.",
    "Liar's RetreatKarthwasten which is overtaken by Falmers.",
    "Mzinchaleft",
    "Mzulftmap)",
    "Nchuand-Zel",
    "Purewater Run",
    "Raldbthar",
    "Reachwind Eyrie",
    "Ruins of Bthalft",
    "Ruins of Rkund",
    "Shimmermist Cave",
    "Sightless Pit",
    "Tolvald's Cavesouth-southeast of Ansilvund.",
    "Tower of Mzark"
]

let militaryForts = [
    "Bloodlet Throne",
    "Broken Tower Redoubtas the Volkihar vampire clan's home.",
    "Cracked Tusk Keep",
    "Darklight Tower",
    "Driftshade Refuge",
    "Faldar's Tooth",
    "Fellglow Keep",
    "Fort Amolelemental mages.",
    "Fort Dunstad",
    "Fort Fellhammerand General Falx Carius.",
    "Fort Greenwallbandits.",
    "Fort Greymoormap)",
    "Fort Hraggstad",
    "Fort Kastavby warlocks and skeletons.",
    "Fort Neugrad",
    "Fort Snowhawk",
    "Fort SungardFalkreath Hold, initially occupied by Forsworn.",
    "Gallows Rock",
    "Harmugstahl",
    "High HrothgarNeloth's former apprentice Ildari Sarothril.",
    "Ilinalta's Deep",
    "Mistwatch",
    "Eastmarch, just southeast of the Atronach Stone on the edge of the hot springs.",
    "Morvunskar",
    "Nightcaller Temple",
    "Northwatch Keep",
    "Treva's Watch",
    "Western Watchtower"
]

let mines = [
    "Bilegulch Minenear the entrance. to a group of rieklings.",
    "Cidhna Mineserves",
    "Dushnikh Mineentrance.",
    "Embershard Mine",
    "Fenn's Gulch Minemap)",
    "Fort Fellhammer",
    "Gloombound Mineentrance.",
    "Goldenrock Mine",
    "Halted Stream Mine",
    "Iron-Breaker Mine",
    "Kolskeggr Mine",
    "Left Hand Mine",
    "Lost Prospect Mine",
    "Mor Khazgur Mineentrance.",
    "Northwind Mine",
    "Quicksilver Mine",
    "Redbelly Mine",
    "Rockwallow Mineof Solitude.",
    "Sanuarach Mine",
    "Steamscorch Mine",
    "Soljund's Sinkholemap)",
    "Whistling Mine"
]

let nordicRuins = [
    "Angarvundenorthwest of Avanchnzel.",
    "Ansilvund",
    "Arcwind Pointmap)",
    "Bleak Falls Barrow",
    "Blind Cliff BastionForsworn.",
    "Bromjunaar Sanctuarybuilding in Labyrinthian.",
    "Dead Men's Respitespiders.",
    "Deepwood Redoubt",
    "Dustman's Cairn",
    "Folgunthur",
    "ForelhostCall shout.",
    "Frostmere CryptStone.",
    "Geirmund's Hallskeevers.",
    "Hag Rock Redoubt",
    "Hag's End",
    "High Gate Ruinsof the Icerunner.",
    "Hillgrund's Tomb",
    "Ironbind Barrowtomb of a long dead warlord.",
    "Kilkreath Ruins",
    "Korvanjund",
    "Labyrinthianareas.",
    "Lost Valley Redoubt",
    "Ragnvald",
    "Rannveig's FastMorthal.",
    "Saarthal",
    "Shalidor's Maze",
    "Shriekwind Bastion",
    "Shroud Hearth Barrow",
    "Silent Moons Camp",
    "Silverdrift LairNightgate Inn.",
    "Skuldafn",
    "Snow Veil Sanctum",
    "Twilight Sepulcherresting place for the Skeleton Key.",
    "Ustengravskeletons, and frostbite spiders. shades and draugr.",
    "Valthume",
    "VolskyggeDeepwood Redoubt and Lost Echo Cave.",
    "VolunruudWhisper shout, as well as the treasure and dead body of the Tongue Chieftain Kvenel. and spiders.",
    "Yngol Barrow",
    "Ysgramor's Tombspiders.",
    "Ruins",
    "Four Skull Lookouteast of Blind Cliff Cave, containing bandits.",
    "Hamvir's RestDustman's Cairn.",
    "Journeyman's Nook",
    "Kjenstag RuinsStormcloak Camp.",
    "Lost Valkyggmap)",
    "North Skybound Watch",
    "Roadside Ruins",
    "Skytemple RuinsHrothmund's Barrow, guarded by werebears.",
    "Windward Ruins",
    "Yorgrim Overlooksouth of Winterhold."
]

let imperialTowers = [
    "Abandoned Prisondrowned prisoners.",
    "Falkreath Watchtower",
    "Pinefrost Towerand northwest of Volskygge.",
    "Refugees' Rest",
    "Rift Watchtower",
    "Shor's Watchtowerof Riften.",
    "Snowpoint BeaconDriftshade Refuge and due east of Fort Fellhammer.",
    "Stendarr's Beacon",
    "Whitewatch Tower",
    "Widow's Watch Ruinshag.",
    "Nordic Towers",
    "Bannermist Towerand Hunter's Rest, and east of Knifepoint Ridge.",
    "Bleakwind BluffRorikstead on an outcrop of rock.",
    "Cradle Stone Towermap)",
    "Dead Crone Rockjust above Hag Rock Redoubt.",
    "Nilheim",
    "Peak's Shade Tower",
    "South Skybound Watch",
    "Sundered Towers",
    "Valtheim Towers"
]